name: personal
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel
  - networkx
  - streamlit=1.29
  - graphviz
  - pandas
  - scikit-learn